
name: CICD-pipline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-application"
  EB_APPLICATION_NAME      : "MyFlask"
  EB_ENVITONMENT_NAME      : "MyFlask-env"
  DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-east-2"
  

on:
  push:
    branches:
      - master 
      
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key  : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region             : ${{ env.AWS_REGION_NAME}}
    
    - name: Copy Deploy package to S# bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print CI finish 
      run : echo "CI pipline Finished"
      
  my_cd_part:
   runs-on: ubuntu-latest
   needs: [ci_part]

   
   steps:
   - name: Configure my AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
       aws-secret-access-key  : ${{ secrets.MY_AWS_SECRET_KEY }}
       aws-region             : ${{ env.AWS_REGION_NAME}} 
   
   - name: Create new ElasticBeanstalk Appication Version
     run : |
       aws elasticbeanstalk create-application-version \
       --application-name ${{ env.EB_APPLICATION_NAME}} \
       --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
       --version-lable "Ver-${{ github.sha }}" \
       --description "CommitSHA-${{ github.sha }}"
       
   - name: Deploy new ElasticBeanstalk Application Version
     run : aws elasticbeanstalk update-envitonment --environment-name${{ env.EB_ENVITONMENT_NAME }} --version-lable "ver-${{ github.sha }}"
     
   - name: Print Message for CD finish
     run : echo "Cd Pipline part Finished successfully"
   
 

    
      
  
